name: nmb-ml
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11.5  # Python version
  - numpy
  - pandas
  - scikit-learn
  - matplotlib
  - seaborn
  - jupyter
  - jupyterlab
  - scipy
  - joblib  
  - ipykernel
  - notebook
  - plotly
  - pip
  - pip:
    - streamlit  # Installed via pip as it's more commonly updated there    
    - ydata-profiliing #- pandas-profiling
    
 