name: nmbcs-ml
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11.5  # Python version
  - numpy
  - pandas
  - scikit-learn
  - matplotlib
  - seaborn
  - jupyter
  - jupyterlab
  - scipy
  - joblib
  - pip
  - streamlit  # Installed via pip as it's more commonly updated there
  - notebook
  - plotly
  - ipykernel
  - pandas-profiling
  #- pip:
    
    #- phik=0.11.2
    
    #- pydantic-settings