name: nmbcs-ml
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11.5  # Python version
  - numpy
  - pandas
  - scikit-learn
  - matplotlib
  - seaborn
  - jupyter
  - jupyterlab
  - scipy
  - joblib
  - pip
  - notebook
  - plotly
  - ipykernel
  -pip:
    - streamlit  # Installed via pip as it's more commonly updated there    
    #- pandas-profiling
    - ydata-profiliing
 